title: Whitehat.NG
description: Nigeria Cyberspace - ISAC + People CERT.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

github:
  twitter_url: https://whitehat.ng
  linkedin_url: https://whitehat.ng
