title: Whitehat.NG
description: Nigeria's Cyberspace - ISAC + People CERT.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

github:
  twitter_url: advisory-intel
  linkedin_url: people-cert
  

